# Generated by Django 4.2.5 on 2024-03-13 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerShareStation',
            fields=[
                ('lat', models.FloatField(max_length=100)),
                ('lon', models.FloatField(max_length=100)),
                ('uuid', models.CharField(max_length=100)),
                ('deviceId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PowerShareOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickupTime', models.DateTimeField()),
                ('returnTime', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pickupStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_up_station', to='powershare.powersharestation')),
                ('returnStation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_station', to='powershare.powersharestation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
