# Generated by Django 4.2.5 on 2023-12-04 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('powershare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='powershareorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='powershareorder',
            name='pickupStation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_up_station', to='powershare.powersharestation'),
        ),
        migrations.AlterField(
            model_name='powershareorder',
            name='returnStation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_station', to='powershare.powersharestation'),
        ),
    ]
